version: "3.9"

services:
  port-forward:
    restart: always
    container_name: port-forward
    image: benwk/aks-port-forward:local-latest
    ports:
      - 8080:${LOCAL_PORT}
    env_file:
      - .env
    volumes:
      - ~/.kube/config:/root/.kube/config
    network_mode: bridge