apiVersion: v1
kind: Service
metadata:
  name: mysql-external
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 13306
      targetPort: 3306
  selector:
    app: mysql
  type: LoadBalancer