name: Port Forward Image

on:
  push:
    branches:
      - release/port-forward-credentials
      - release/port-forward-service
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: export METHOD=$(echo ${{ github.ref_name }} | awk -F '-' '{print $3}')
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: |
            LOGIN_METHOD=$METHOD
          push: true
          file: dockerfiles/port-forward.Dockerfile
          tags: |
            benwk/aks-port-forward:$METHOD-${{ github.run_number }}
            benwk/aks-port-forward:$METHOD-latest
